# Generated by Django 6.1.1 on 2026-09-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(help_text='Clave primaria numérica autoincremental del estudiante.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Nombre(s) del estudiante.', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido(s) del estudiante.', max_length=100, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'student',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(help_text='Clave primaria numérica autoincremental del docente.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Nombre(s) del profesor.', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido(s) del profesor.', max_length=100, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'teacher',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(help_text='Clave primaria numérica autoincremental del curso.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la asignatura académica.', max_length=150, verbose_name='Nombre del Curso')),
                ('teacher', models.ForeignKey(db_column='teacher_id', help_text='Docente que imparte la asignatura (Relación N:1 con Teacher).', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.teacher', verbose_name='Profesor Asignado')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(db_column='course_id', help_text='Asignatura en la cual está inscrito el estudiante.', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academic.course', verbose_name='Asignatura')),
                ('student', models.ForeignKey(db_column='student_id', help_text='Estudiante que se inscribe en el curso.', on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='academic.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción de Curso',
                'verbose_name_plural': 'Inscripciones de Cursos',
                'db_table': 'student_course',
                'ordering': ['student', 'course'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
